### ISSUE TITLE
Could you please provide dataset format?

### ISSUE THREAD

**Issue by Vergissmeinnic** [shoutOutYangJie/MobileOne#10]
Hello,I wanna train my model,but I don't know the format of the dataset.
Could you please provide it?Thank you.
The project brought me a lot of help,I really need it.
Please!

**Comment by Vergissmeinnic** [comment]
I know how to train,but what's the dataset?
I wanna the format,please.

**Comment by shoutOutYangJie** [comment]
> I know how to train,but what's the dataset? I wanna the format,please.

ImageNet 1k. just as same as RepVGG
