### ISSUE TITLE
question about merge conv and bn

### ISSUE THREAD

**Issue by kache1995** [shoutOutYangJie/MobileOne#14]
hi，when i read your code，i find that a question about merge conv and bn.
when merge conv and bn：
![image](https://user-images.githubusercontent.com/43060760/200467535-94995fdf-3418-4e5d-b21a-2fcf95e96800.png)
why your code ：
    std = (running_var + eps).sqrt()
    t = (gamma / std).reshape(-1, 1, 1, 1)
    return kernel * t, beta - running_mean * gamma /  std

why you not use conv's bias, i think the result should be:
        weight = conv_weight * bn_weight.view(out_channels, 1, 1, 1) / bn_std.view(out_channels, 1, 1, 1)
    
         bias = bn_weight * (conv_bias - bn_mean) / bn_std + bn_bias

**Comment by kache1995** [comment]
i get it, your conv without bias

**Comment by shoutOutYangJie** [comment]
@kache1995  Yes, because BN exists, I don't use bias in Conv layers, which is also well-known operation.
