### ISSUE TITLE
How did you check the model and depolyment model  results consistency

### ISSUE THREAD

**Issue by zjuybh** [shoutOutYangJie/MobileOne#3]
Hi, I find that using repvgg_model_convert function,  the output of the model and the deployed model are very different using the same input tensor. How did you check the model and depolyment model  results consistency ?

**Comment by zjuybh** [comment]
`tmp_model = copy.deepcopy(model)
    for module in tmp_model.modules():
        if hasattr(module, 'switch_to_deploy'):
            module.switch_to_deploy()
    print('swith done. Checking....')
    deploy_model = mobileone_s0(deploy=True)
    deploy_model.eval()
    deploy_model.load_state_dict(tmp_model.state_dict())

    input = {'image': torch.randn((1, 3, 112, 112))}
    a = model(input)
    b = deploy_model(input)
    print(a.shape)
    print(b.shape)
    print((a-b).mean())`

I find (a-b).mean() is very large

**Comment by shoutOutYangJie** [comment]
please set model.eval. I indeed check my model





------------------ Original ------------------
From: zjuybh ***@***.***&gt;
Date: Thu,Jun 30,2022 1:15 PM
To: shoutOutYangJie/MobileOne ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [shoutOutYangJie/MobileOne] How did you check the model anddepolyment model  results consistency (Issue #3)

**Comment by zjuybh** [comment]
Thank you very much. with model.eval(), it helps a lot. the (a-b).sum() ranges from (-0.4, 0.03) for torch.randn((1, 3, 112, 112)). Is it acceptable, right ?

**Comment by shoutOutYangJie** [comment]
yes， it Is normal





------------------ Original ------------------
From: zjuybh ***@***.***&gt;
Date: Thu,Jun 30,2022 1:31 PM
To: shoutOutYangJie/MobileOne ***@***.***&gt;
Cc: shoutOutYangJie ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [shoutOutYangJie/MobileOne] How did you check the model and depolyment model  results consistency (Issue #3)





 
Thank you very much. with model.eval(), it helps a lot. the (a-b).sum() ranges from (-0.4, 0.03) for torch.randn((1, 3, 112, 112)). Is it acceptable, right ?

**Comment by shoutOutYangJie** [comment]
ofcourse，please see my readme





------------------ Original ------------------
From: zjuybh ***@***.***&gt;
Date: Thu,Jun 30,2022 1:12 PM
To: shoutOutYangJie/MobileOne ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [shoutOutYangJie/MobileOne] How did you check the model anddepolyment model  results consistency (Issue #3)
