### ISSUE TITLE
why use normal stem for self.stage0？

### ISSUE THREAD

**Issue by shensheng272** [shoutOutYangJie/MobileOne#5]
self.stage0  look like normal stem, rather than mobileOne block in paper. Any reason why?

By the way, use mobileOne block as stem might cause huge acc drop in cifar100 (50%+)

**Comment by shoutOutYangJie** [comment]
I test mode's Flops when using mobileOne block as stem later, but FLOPS is inconsistent with paper.
However, when I use normal Conv block ,  the flops can be the same. 
So I guess the paper make a mistake.
@shensheng272

**Comment by shoutOutYangJie** [comment]
For second question, I don't test model when using mobileone block as stem layer.
