### ISSUE TITLE
repvgg_model_convert function should't have the "x", please confirm it

### ISSUE THREAD

**Issue by fsfing** [shoutOutYangJie/MobileOne#7]
o = deploy_model(x)
this "x" should't have.

**Comment by shoutOutYangJie** [comment]
Please illustrate question with which line in which file.  Thank you.

**Comment by fsfing** [comment]
mobileone.py 
359 line

**Comment by shoutOutYangJie** [comment]
> mobileone.py 359 line

just set arg "input" as None, you don't need it.
