### ISSUE TITLE
[BUG] Skip connection should be always added to DW branches.

### ISSUE THREAD

**Issue by grygielski** [shoutOutYangJie/MobileOne#9]
Hi @shoutOutYangJie, I've noticed that you have a bug in your MobileOne implementation:
https://github.com/shoutOutYangJie/MobileOne/blob/48ca6c97cb95d672da3783ec812eafaa443da4bb/mobileone.py#L77

You are adding DW BN layer based on `in_channels == out_channels` condition but it should be always added because for DW part input channels are always equal to output channels. This condition should be only checked for PW part as there might be channel change.

**Comment by shoutOutYangJie** [comment]
Oh, yes, thank you. I will refer your issue to ReadMe. Because I don't plan to retrain the model, so I don't want to rewrite it.
 Thank you again.

**Comment by shoutOutYangJie** [comment]
and the official mobileone source code has been opened.
